[bindings.kotlin]
package_name = "dev.oneam.midnightmobile.uniffi"
cdylib_name = "midnight_mobile_runtime"
android = true

[bindings.swift]
module_name = "MidnightMobileRuntime"
ffi_module_name = "MidnightMobileRuntime"
ffi_module_filename = "MidnightMobileRuntimeFFI"
cdylib_name = "midnight_mobile_runtime"
