import {
  createMidnightLocalProver,
  MidnightLocalProverError,
  type MidnightLocalProverConfiguration,
} from "@1am/midnight-mobile/local-prover";

import type { ExamplePlatform } from "./mock-services";
import type { NativeSmokeReport, NativeSmokeStep } from "./native-smoke";

/**
 * Public, synthetic proving artifacts from the pinned ledger release. The
 * bytes are deliberately not checked into this repository. Run the staging
 * command described in the example README to verify and copy them into the
 * native app bundle.
 */
const ARTIFACTS = {
  bls: {
    path: "bls_midnight_2p15",
    size: 6_291_844,
    sha256: "724c7c3d779148bb113c7ee9c034b2f27db16e6bdf315fde90105a9bad00b1de",
  },
  proverKey: {
    path: "zswap/9/spend.prover",
    size: 11_020_001,
    sha256: "19d234b5c68b7212ad6b0ec9334a95594748154128f3704eb576bcc843cc5c45",
  },
  verifierKey: {
    path: "zswap/9/spend.verifier",
    size: 2_311,
    sha256: "544554effd7ae9fb9063be52a9ec2a986756301071fcd97bb4598fb45a335658",
  },
  ir: {
    path: "zswap/9/spend.bzkir",
    size: 1_294,
    sha256: "7cb5bbcf67cb212a3336fb439a77e8f32f0aa8a56185c8e1247d6cbfc7300205",
  },
} as const;

/** Generated by the repository's deterministic prover-request examples. */
const CHECK_REQUEST_BASE64 =
  "bWlkbmlnaHQ6KHByb29mLXByZWltYWdlLXZlcnNpb25lZCxvcHRpb24od3JhcHBlZC1pcikpOgE1AQAAAAAAJQNvB4vZ3vw6Ok7SQsgklAXmaV4z/royS5PgQiHxUNn3cQAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAT1Am9YDnRBKomrRnXQ992S5phJbgEMyL7FYVbynsXen2IqAAAAc8GyCR6/kFpC0040zYs0Wg5xQ/NXFoUojB61uxwAH9cNAA0BwEEBBAQAQQEEBAhABARz//////7////+W/7/AqS9UwXYoQkI2DkzSH2dKVOn7XNzjoknFS2za1gOkt4AjOL73C8CEMxI4fCXpmnaG5FCfSZgNAQEBMEBBAQEQAQEgDEBbyLfHXzV/Zd29Y1AAJeApLCsllWzDOniqUDSZl6KiHtEAEUChQJABAQEDEQEBIAAAEUCwEEBBAQUMAQIAEAEBAQIRAQIc//////+/////lv+/wKkvVMF2KEJCNg5M0h9nSlTp+1zc//////+/////lv+/wKkvVMF2KEJCNg5M0h9nSlTp+1zc5KFfqWiVv6AYLebBqu/d1DzZ7q/D9hwpmoqFUpayCInc6Z39I7pVaXnGd7jQOqevt15uqqKtpoTpF6svJ4W5oFkRQIIBAAAAFBtaWRuaWdodC96c3dhcC9zcGVuZAA=";
const PROVE_REQUEST_BASE64 =
  "bWlkbmlnaHQ6KHByb29mLXByZWltYWdlLXZlcnNpb25lZCxvcHRpb24ocHJvdmluZy1kYXRhKSxvcHRpb24oZnItYmxzKSk6ATUBAAAAAAAlA28Hi9ne/Do6TtJCyCSUBeZpXjP+ujJLk+BCIfFQ2fdxAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABPUCb1gOdEEqiatGddD33ZLmmEluAQzIvsVhVvKexd6fYioAAABzwbIJHr+QWkLTTjTNizRaDnFD81cWhSiMHrW7HAAf1w0ADQHAQQEEBABBAQQECEAEBHP//////v////5b/v8CpL1TBdihCQjYOTNIfZ0pU6ftc3OOiScVLbNrWA6S3gCM4vvcLwIQzEjh8JemadobkUJ9JmA0BAQEwQEEBARABASAMQFvIt8dfNX9l3b1jUAAl4CksKyWVbMM6eKpQNJmXoqIe0QARQKFAkAEBAQMRAQEgAAARQLAQQEEBBQwBAgAQAQEBAhEBAhz//////7////+W/7/AqS9UwXYoQkI2DkzSH2dKVOn7XNz//////7////+W/7/AqS9UwXYoQkI2DkzSH2dKVOn7XNzkoV+paJW/oBgt5sGq793UPNnur8P2HCmaioVSlrIIidzpnf0julVpecZ3uNA6p6+3Xm6qoq2mhOkXqy8nhbmgWRFAggEAAAAUG1pZG5pZ2h0L3pzd2FwL3NwZW5kAAA=";

function decodeBase64(value: string): Uint8Array {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes;
}

/** Returns fresh copies of the pinned synthetic local-prover requests. */
export function localProverRequests(): {
  readonly check: Uint8Array;
  readonly prove: Uint8Array;
} {
  return {
    check: decodeBase64(CHECK_REQUEST_BASE64),
    prove: decodeBase64(PROVE_REQUEST_BASE64),
  };
}

function uri(platform: ExamplePlatform, path: string): string {
  return platform === "android"
    ? `asset://local-prover/${path}`
    : `bundle://LocalProverArtifacts/${path}`;
}

function file(
  platform: ExamplePlatform,
  artifact: (typeof ARTIFACTS)[keyof typeof ARTIFACTS],
) {
  return {
    uri: uri(platform, artifact.path),
    size: artifact.size,
    sha256: artifact.sha256,
  } as const;
}

/** Builds the SDK configuration for the verified spend circuit. */
export function localProverConfiguration(
  platform: ExamplePlatform,
): MidnightLocalProverConfiguration {
  return {
    parameters: [{ k: 15, file: file(platform, ARTIFACTS.bls) }],
    circuits: [
      {
        keyLocation: "midnight/zswap/spend",
        proverKey: file(platform, ARTIFACTS.proverKey),
        verifierKey: file(platform, ARTIFACTS.verifierKey),
        ir: file(platform, ARTIFACTS.ir),
      },
    ],
  };
}

function describeFailure(failure: unknown): string {
  if (failure instanceof MidnightLocalProverError) return failure.code;
  // Do not put native messages, paths, or artifact details on screen.
  return "NATIVE_INTERNAL";
}

/**
 * Runs real local `check` and `prove` calls against the staged native
 * artifacts. A missing development build or missing artifacts is reported as
 * a failure; this function never substitutes a synthetic proof response.
 */
export async function runLocalProverSmokeTest(
  platform: ExamplePlatform,
): Promise<NativeSmokeReport> {
  const steps: NativeSmokeStep[] = [];
  let prover: Awaited<ReturnType<typeof createMidnightLocalProver>> | null =
    null;
  try {
    const requests = localProverRequests();
    const started = Date.now();
    prover = await createMidnightLocalProver(
      localProverConfiguration(platform),
    );
    steps.push({
      name: "configure native local prover",
      ok: true,
      detail: `${String(Date.now() - started)} ms`,
    });

    const checkStarted = Date.now();
    const checkResponse = await prover.check(requests.check);
    steps.push({
      name: "run native check",
      ok: checkResponse.length > 0,
      detail: `${String(checkResponse.length)} bytes in ${String(Date.now() - checkStarted)} ms`,
    });
    if (checkResponse.length === 0) {
      throw new MidnightLocalProverError("CHECK_FAILED");
    }

    const proveStarted = Date.now();
    const proof = await prover.prove(requests.prove);
    steps.push({
      name: "run native prove",
      ok: proof.length > 0,
      detail: `${String(proof.length)} bytes in ${String(Date.now() - proveStarted)} ms`,
    });
    if (proof.length === 0) {
      throw new MidnightLocalProverError("PROOF_FAILED");
    }
  } catch (failure: unknown) {
    steps.push({
      name: "native local prover",
      ok: false,
      detail: describeFailure(failure),
    });
  } finally {
    if (prover !== null) {
      try {
        await prover.close();
      } catch (failure: unknown) {
        steps.push({
          name: "close native local prover",
          ok: false,
          detail: describeFailure(failure),
        });
      }
    }
  }
  return { steps, passed: steps.length > 0 && steps.every((step) => step.ok) };
}
